mysql-account: 2023211454
spring:
  datasource:
    url: jdbc:mysql://120.46.159.231/${mysql-account}
    username: ${mysql-account}
    password: ${mysql-account}
##    默认开启程序启动执行sql文件
#  sql:
#    init:
#      mode: always

logging:
  level:
    sql: debug
    com:
      morgan:
        demo01: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'