mysql-account: 2023211454
spring:
  datasource:
    url: jdbc:mysql://120.46.159.231/${mysql-account}
    username: ${mysql-account}
    password: ${mysql-account}
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
logging:
  level:
    sql: debug
    com:
      morgan:
        demo01: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'